version: 2.1

jobs:
  build:
    working_directory: ~/Python-Project
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 FirstPyFile.py

workflows:
  build_and_test:
    jobs:
      - build